version: "3.9"
services:
  webforms-link-generator:
    image: ${IMAGE_URL:?set IMAGE_URL}:${IMAGE_TAG:?set IMAGE_TAG}
    networks:
      - traefik
    deploy:
      labels:
        traefik.enable: "true"
        traefik.swarm.network: "traefik"
        traefik.http.routers.webforms-link-generator.service: "${TRAEFIK_SERVICE:?Set TRAEFIK_SERVICE}"
        traefik.http.routers.webforms-link-generator.rule: "Host(`${APP_HOSTNAME:?Set APP_HOSTNAME}`)"
        traefik.http.routers.webforms-link-generator.entrypoints: "${TRAEFIK_ENTRYPOINT:?Set TRAEFIK_ENTRYPOINT}"
        traefik.http.routers.webforms-link-generator.tls: "true"
        traefik.http.services.webforms-link-generator.loadbalancer.server.port: "${TRAEFIK_PORT:?Set TRAEFIK_PORT}"
    environment:
      PORT: 3000
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:?set ADMIN_PASSWORD}"
      SESSION_SECRET: "${SESSION_SECRET:?set SESSION_SECRET}"
      ADMIN_GATEWAY_SECRET: "${ADMIN_GATEWAY_SECRET:?set ADMIN_GATEWAY_SECRET}"
      API_URL: "${API_URL:?set API_URL}"
      COOKIE_SECURE: "${COOKIE_SECURE:-true}"

networks:
  traefik:
    external: true
